### ISSUE TITLE
In progress?

### ISSUE THREAD

**Issue by jamunano** [thebetioplane/OsuReplayEditorV2#1]
i am just wondering if this is still an ongoing project or not. id love to see this complete!

**Comment by thebetioplane** [comment]
No idea, I left it in a state where it can still minimally edit some osr files, but I think some people reported bugs that probably still persist (major bugs as in some replays don't get saved properly).

I was feeling like revamping this project, but if I were to do so (or if anyone wants to build on this), then I wouldn't continue from this code base, not just due to bad practices but more importantly this code is dependent on Microsoft XNA, a discontinued framework. OpenTK isn't bad if C# were to still be used, but I wouldn't even want to set that restriction... I see C++ as maybe being a better choice.
