### ISSUE TITLE
Can't read osu!.db

### ISSUE THREAD

**Issue by banana-man95** [thebetioplane/OsuReplayEditorV2#7]
I get this error

Error

Can't load osu!.db. Try deleting it and letting osu! rebuild it when you relaunch the game.

I tried deleting osu!.db but and letting osu! rebuild it but it still doesn't work

**Comment by moorf** [comment]
Sadly this project seems to be broken. 
Fixed this problem by compiling the program by myself (you need to add BassNetRegister.cs from [CTB-Replay-Editor](https://github.com/Azukee/CTB-Replay-Editor) to the project contents and Bass.Net.dll to project links and set Specific Version property to false), but Replay Reader turns out to be broken, the program simply says it's not a replay file.
You can take files from [CTB-Replay-Editor](https://github.com/Azukee/CTB-Replay-Editor) to fix this, but for now, I'm lazy to do that.
Good luck!

**Comment by thebetioplane** [comment]
I have created a version 3 to address many problems : https://github.com/thebetioplane/osuReplayEditorV3
